export enum AppEvents {
    SET_APP_LOADING = 'SET_APP_LOADING',
    SET_APP_SUCCESS = 'SET_APP_SUCCESS',
    SET_APP_ERROR = 'SET_APP_ERROR'
}

export enum AuthEvents {
    SET_USER_DATA = 'SET_USER_DATA',
    LOGOUT = 'LOGOUT',
    SET_LOADING = 'SET_LOADING',
    SET_SUCCESS = 'SET_SUCCESS',
    SET_ERROR = 'SET_ERROR',
    SET_LOGIN_STATUS = 'SET_LOGIN_SUCCESS',
    SET_REGISTER_STATUS = 'SET_REGISTER_STATUS',
    SET_FORGOT_STATUS = 'SET_FORGOT_STATUS',
    SET_PASSWORD_CHANGE  = 'SET_PASSWORD_CHANGE'
}


export enum PacksEvents {
    SET_CARD_PACKS = 'SET_CARD_PACKS',
    SET_CARD_PACKS_LOADING = 'SET_CARD_PACKS_LOADING'
}

export enum CardsEvents {
    SET_CARDS= 'SET_CARDS',
    SET_CARDS_LOADING='SET_CARDS_LOADING'
}


export enum FindPaginationEvents {
    SET_PRODUCT_NAME = 'FIND-PAGINATION/SET-PRODUCT-NAME',
    SET_MIN_MAX = 'FIND-PAGINATION/SET-MIN-MAX',
    SET_PAGE_COUNT = 'FIND-PAGINATION/SET-PAGE-COUNT',
    SET_CARD_PACKS_TOTAL_COUNT = 'FIND-PAGINATION/SET-CARD-PACKS-TOTAL-COUNT',
    SET_CURRENT_PAGE = 'FIND-PAGINATION/SET-CURRENT-PAGE',
    SET_SORT = 'FIND-PAGINATION/SET-SORT'
}